### PR TITLE
Use itemID instead of name for internationalization

### PR DESCRIPTION
**Pull request by JulianIntronati**
- Fixed amount of Wintersbite 20 -> 8
- Changed code to check on itemID instead of name

### CODE REVIEW

**Comment by JulianIntronati** [comment]
@saimpot I had to rebase 2 times, could you consider this pull request ? It just permit other language than EN to use your work.
I kept in the lua file the comment with item name for convenience.

**Comment by saimpot** [comment]
Hey. Thanks for the pr. I will review later today after I'm done with work!

**Comment by saimpot** [comment]
@JulianIntronati hey mate running a bit late but rest assured this will get merged once I check it out!

**Comment by saimpot** [comment]
@JulianIntronati It all looks good to me. 👍  

Just for an interesting tidbid of information, the structure "name" = {id,requestedItemId,etc} happened because at first I was "parsing" the tooltip text line by line to find the amount of waylaid supplies needed per box, and which item was needed. However, that process was ground to a halt because while I could extra 6 and "Copper Bar" from "6 copper bars" in the text, I didn't have any way to get the item ID from the item name, so that way the very wrongly structured table was born!

**Comment by JulianIntronati** [comment]
@saimpot No problem with the structure, developing is going back and forth all the time !
Keep going with your good work, your addon is very useful !

Thank you very much for merging my pull request.

**Pull request merged**
